name: QA
on:
  push:
    branches:
      - "main"
      - "feature/*"
      - "hotfix/*"
      - "release/*"
      - "renovate/*"
  pull_request:

jobs:
  lint:
    uses: canonical/starflow/.github/workflows/lint-python.yaml@main
  test:
    uses: canonical/starflow/.github/workflows/test-python.yaml@main
    with:
      lowest-python-version: "3.10"
      fast-test-platforms: '["ubuntu-22.04", "ubuntu-24.04", "ubuntu-24.04-arm"]'
      slow-test-platforms: '["ubuntu-22.04", "ubuntu-24.04", "ubuntu-24.04-arm"]'
